name: Automatisation des tests DevSecOps
on: push
jobs:
  Dependances:
    runs-on: ubuntu-24.04
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v5
      - name: Dependances
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: requirements.txt
          scanners: vuln
          severity: HIGH,CRITICAL
          exit-code: '1'
  Dockerfile:
    runs-on: ubuntu-24.04
    needs: Dependances
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v5
      - name: Test Dockerfile
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: Dockerfile
          severity: HIGH,CRITICAL
          exit-code: '1'
      - name: Construire l'image Docker
        run: |
          test -f Dockerfile
          docker build --file Dockerfile --tag breakableflask:ci .
  Deploy:
    runs-on: ubuntu-24.04
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
