name: Automatisation des tests DevSecOps
on: push
jobs:
  Dependances:
    runs-on: ubuntu-24.04
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v5
      - name: Dependances
        run: |
          python -m pip install --upgrade pip pip-audit
          pip-audit --requirement requirements.txt
  Dockerfile:
    runs-on: ubuntu-24.04
    needs: Dependances
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v5
      - name: Test Dockerfile
        run: |
          test -f Dockerfile
          docker build --file Dockerfile --tag breakableflask:ci .
  Deploy:
    runs-on: ubuntu-24.04
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
